### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by sumfish0104** [bigmms/color-transferred-cnn-dehazing#1]
hi~ When i tested you code, i encountered the following problem. could you help me solve the problem? i'll appreciate it.
![Uploading 1648457746(1).png…]()

**Comment by sumfish0104** [comment]
Traceback (most recent call last):
  File "demo.py", line 136, in <module>
    deHaze.run()
  File "demo.py", line 130, in run
    self.first_step()
  File "demo.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "demo.py", line 94, in first_step
    l_pres = load_model(self.Models['model_L']).predict(self.firstStepInputImages)
  File "D:\anaconda\lib\site-packages\keras\models.py", line 233, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\anaconda\lib\site-packages\keras\models.py", line 307, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "D:\anaconda\lib\site-packages\keras\layers\__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "D:\anaconda\lib\site-packages\keras\utils\generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\anaconda\lib\site-packages\keras\engine\topology.py", line 2450, in from_config
    process_layer(layer_data)
  File "D:\anaconda\lib\site-packages\keras\engine\topology.py", line 2419, in process_layer
    custom_objects=custom_objects)
  File "D:\anaconda\lib\site-packages\keras\layers\__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "D:\anaconda\lib\site-packages\keras\utils\generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\anaconda\lib\site-packages\keras\layers\core.py", line 694, in from_config
    function = func_load(config['function'], globs=globs)
  File "D:\anaconda\lib\site-packages\keras\utils\generic_utils.py", line 200, in func_load
    code = marshal.loads(code.encode('raw_unicode_escape'))
ValueError: bad marshal data (unknown type code)
Done

**Comment by kumarballapavan** [comment]
I also get the same issue. I request you to kindly help to resolve the issue!
